# Generated by Django 4.2.6 on 2024-02-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagespost',
            name='title',
        ),
    ]
